# Generated by Django 3.2.9 on 2022-01-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_user',
        ),
    ]
