# Generated by Django 3.2.9 on 2022-01-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=models.TextField(default='some string'),
        ),
    ]
